### ISSUE TITLE
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::BFloat16

### ISSUE THREAD

**Issue by MaggieK410** [hitz-zentroa/GoLLIE#20]
Hi, 
thank you very much for sharing your model on Github and Huggingface! I am trying to follow the Event Extraction Notebook (https://github.com/hitz-zentroa/GoLLIE/blob/main/notebooks/Event%20Extraction.ipynb) and am facing the follwing error when using model.generate: 

RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::BFloat16

I am using the following specs:
accelerate                0.30.1 
bitsandbytes            0.42.0
black                        24.4.2 
cuda-cudart               12.1.105
cuda-cupti                12.1.105      
cuda-libraries            12.1.0         
cuda-nvrtc                12.1.105            
cuda-nvtx                 12.1.105  
cuda-opencl               12.5.39     
cuda-runtime              12.1.0    
cuda-version              12.5     
nvidia-nvtx-cu12          12.1.105 
peft                      0.11.1
torch                     2.1.0 
torchaudio                2.2.0   
torchvision               0.17.0     
tqdm                      4.66.4      
transformers              4.41.2            
triton                    2.3.0 
flash-attn                2.5.9.post1

I have faced the same issue with flash-attn  2.5.8  and am honestly having a lot of problems finding a combination of pytorch+flash attn+ cuda that works. 

Full traceback:
    model_output=model.generate(
  File /lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
  File "/lib/python3.9/site-packages/transformers/generation/utils.py", line 2397, in _sample
    outputs = self(
  File /lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1164, in forward
    outputs = self.model(
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 968, in forward
    layer_outputs = decoder_layer(
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 713, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 327, in forward
    query_states = self.q_proj(hidden_states)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::BFloat16

Thank you very much for your help!

**Comment by MaggieK410** [comment]
Okay, so with a bit of digging I found the solution from this thread: https://github.com/huggingface/peft/issues/1515. The key is to add the following to the code:

`with torch.cuda.amp.autocast():
    model_output=model.generate(...)`

This solved the issue for me.

**Comment by ikergarcia1996** [comment]
Hi @MaggieK410 !

Thank you for sharing your solution!!

I just want to point out that this issue usually happens when using GoLLIE without `use_flash_attention=True`, without our custom flash attention implementation, GoLLIE achieves lower F1 scores.  In the future, we will release new models without this limitation

```python
model, tokenizer = load_model(
    inference=True,
    model_weights_name_or_path="HiTZ/GoLLIE-7B",
    quantization=None,
    use_lora=False,
    force_auto_device_map=True,
    use_flash_attention=True,
    torch_dtype="bfloat16",
)
```

**Comment by MaggieK410** [comment]
Hi @ikergarcia1996 thank you for the response. I thought, I had flash attention enabled, but realized, I didn't. Unfortunately, I am having a lot of difficulties with the flash attention installation and keep getting the following error:

/tmp/tmpxh4177tz/main.c: In function ‘list_to_cuuint64_array’:
/tmp/tmpxh4177tz/main.c:354:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
/tmp/tmpxh4177tz/main.c:354:3: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/tmpxh4177tz/main.c: In function ‘list_to_cuuint32_array’:
/tmp/tmpxh4177tz/main.c:365:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
Traceback (most recent call last):
  File "/homes/mkulcsar/event_extraction/gollie/GoLLIE/ee.py", line 50, in <module>
    model_output=model.generate(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/transformers/generation/utils.py", line 2397, in _sample
    outputs = self(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/homes/mkulcsar/event_extraction/gollie/GoLLIE/src/model/patch_models/modeling_flash_llama.py", line 850, in forward
    outputs = self.model(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/homes/mkulcsar/event_extraction/gollie/GoLLIE/src/model/patch_models/modeling_flash_llama.py", line 740, in forward
    layer_outputs = decoder_layer(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/homes/mkulcsar/event_extraction/gollie/GoLLIE/src/model/patch_models/modeling_flash_llama.py", line 505, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/homes/mkulcsar/event_extraction/gollie/GoLLIE/src/model/patch_models/modeling_flash_llama.py", line 383, in forward
    q, k = self.rotary_emb(q, k, past_len)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/homes/mkulcsar/event_extraction/gollie/GoLLIE/src/model/patch_models/modeling_flash_llama.py", line 227, in forward
    return apply_rotary_emb_func(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/flash_attn/layers/rotary.py", line 122, in apply_rotary_emb
    return ApplyRotaryEmb.apply(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/flash_attn/layers/rotary.py", line 48, in forward
    out = apply_rotary(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/flash_attn/ops/triton/rotary.py", line 202, in apply_rotary
    rotary_kernel[grid](
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/runtime/jit.py", line 550, in run
    bin.c_wrapper(
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/compiler/compiler.py", line 692, in __getattribute__
    self._init_handles()
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/compiler/compiler.py", line 670, in _init_handles
    bin_path = {driver.HIP: "hsaco_path", driver.CUDA: "cubin"}[driver.backend]
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/runtime/driver.py", line 157, in __getattr__
    self._initialize_obj()
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/runtime/driver.py", line 154, in _initialize_obj
    self._obj = self._init_fn()
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/runtime/driver.py", line 187, in initialize_driver
    return CudaDriver()
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/runtime/driver.py", line 77, in __init__
    self.utils = CudaUtils()
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/runtime/driver.py", line 47, in __init__
    so = _build("cuda_utils", src_path, tmpdir)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/common/build.py", line 106, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpxh4177tz/main.c', '-O3', '-I/homes/mkulcsar/.conda/envs/event_extraction_bubble/lib/python3.9/site-packages/triton/common/../third_party/cuda/include', '-I/homes/mkulcsar/.conda/envs/event_extraction_bubble/include/python3.9', '-I/tmp/tmpxh4177tz', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpxh4177tz/cuda_utils.cpython-39-x86_64-linux-gnu.so', '-L/lib64', '-L/lib64']' returned non-zero exit status 1.


I have not been successful in trying to resolve this and disabled flash attention for that reason. Do you know how much it affects the F1 score?

**Comment by MaggieK410** [comment]
Okay, so I did find a solution that worked for me using this thread: https://github.com/MIC-DKFZ/nnUNet/issues/2203. In short: 
1. uninstall torch (and torchaudio and torchvision in case of CUDA) and flash-attn
2. re-install torch with 2.2.0 and make sure triton is triton==2.1.0 and flash-attn

My current packages:
torch                    2.1.0+cu121
torchaudio               2.1.0+cu121
torchvision              0.16.0+cu121
triton                   2.1.0
flash-attn               2.5.9.post1

Thank you for bringing this to my attention! I think its all good now and Im excited to use the model (without decreased F1 score :D) !
